name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rest-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Rodar os testes de API via Controller
      run: npm run test-rest-controller

    - name: Subir a API Rest 
      run: npm run start-rest &

    - name: Esperar a API estar funcionando
      run: sleep 5
    
    - name: Rodar os testes de API via External
      run: npm run test-rest-external